spring:
  h2:
    console:
      enabled: true
      path: '/console'
  datasource:
    url: 'jdbc:h2:file:\\C:\\Users\\julst\\Documents\\Java-ExpiryApp\\expiry-app\\expiry-app\\expiryapp-db;DB_CLOSE_ON_EXIT=FALSE;AUTO_SERVER=TRUE'
  jpa.hibernate.ddl-auto: validate